org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment Properties

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.21-beta

## Mod Properties

mod_id=allthetweaks
mod_name=AllTheTweaks
mod_license=All Rights Reserved
mod_version=3.0.0
mod_group_id=net.allthemods.allthetweaks

## Dependencies

jei_version=29.5.0.26